repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
        args: [ "--unsafe" ]
      - id: check-json
      - id: pretty-format-json
        args: [ "--autofix" ]
      - id: trailing-whitespace
      - id: end-of-file-fixer
- repo: https://github.com/scop/pre-commit-shfmt
  rev: v3.8.0-1
  hooks:
    - id: shfmt
      name: Format shell scripts (shfmt)
      exclude: ^zsh/(p10k\.zsh|zshrc)$
