FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ="Europe/Warsaw"

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
      ca-certificates \
      sudo \
      git \
      make \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash mzebrak \
    && echo 'mzebrak ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER mzebrak
ENV USER=mzebrak
WORKDIR /home/mzebrak

RUN git clone https://github.com/mzebrak/dotfiles.git /home/mzebrak/dotfiles

WORKDIR /home/mzebrak/dotfiles

RUN make core

CMD ["zsh"]
