export ZSH="$HOME/.oh-my-zsh"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

plugins=(
        git
        dotenv
        httpie
        you-should-use
        F-Sy-H
        zsh-autosuggestions
        zsh-docker-aliases
        fzf-tab # fzf-tab should be the last plugin to bind "^I"
)

# >>>>>>>>>>>---------  Settings that must be applied before loading Oh-My-Zsh

# Set the theme
source ~/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme

# Fix slow paste
DISABLE_MAGIC_FUNCTIONS="true"

# <<<<<<<<<<<--------- Settings that must be applied before loading Oh-My-Zsh

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

# >>>>>>>>>>>--------- ZSH

# Apply sensisble zsh settings
source ~/dotfiles/zsh/zshopt
source ~/dotfiles/zsh/zshenv

# Bind C+Space to accept the current suggestion
bindkey '^ ' autosuggest-accept

# Load aliases
source ~/dotfiles/zsh/aliases.zsh

# Apply FZF configuration
source ~/dotfiles/zsh/fzf.zsh

# <<<<<<<<<<<---------  ZSH

# Add local bin to PATH (before loading tools that depend on it)
export PATH="$HOME/.local/bin:$PATH"

# load zoxide
eval "$(zoxide init zsh)"

# load nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

autoload -Uz compinit
zstyle ':completion:*' menu select
fpath+=~/.zfunc
compinit

dexe() {
  if [ $# -eq 0 ]; then
    ssh docker
    return
  fi

  local project="$1"
  shift

  local remote_cmd=""
  case "$project" in
    clive)
      remote_cmd="cd /workspace/clive && \
        . venv/bin/activate && \
        export COLORTERM=truecolor && \
        "
      ;;
    wax)
      remote_cmd="cd /workspace/wax/python && \
        . venv/bin/activate && \
        export COLORTERM=truecolor && \
        "
      ;;
    schemas)
      remote_cmd="cd /workspace/schemas && \
        . venv/bin/activate && \
        export COLORTERM=truecolor && \
        "
      ;;
    *)
      echo "Unknown project: $project"
      return 1
      ;;
  esac

  if [ $# -gt 0 ]; then
    ssh docker-no-remote-command -t "$remote_cmd bash -c '\$@' -- $*"
  else
    ssh docker-no-remote-command -t "$remote_cmd bash -l"
  fi
}

export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).
