export ZSH="$HOME/.oh-my-zsh"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

plugins=(
        git
        dotenv
        httpie
        you-should-use
        F-Sy-H
        zsh-autosuggestions
        zsh-docker-aliases
        fzf-tab # fzf-tab should be the last plugin to bind "^I"
)

# >>>>>>>>>>>---------  Settings that must be applied before loading Oh-My-Zsh

# Set the theme
source ~/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme

# Fix slow paste
DISABLE_MAGIC_FUNCTIONS="true"

# <<<<<<<<<<<--------- Settings that must be applied before loading Oh-My-Zsh

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

# >>>>>>>>>>>--------- ZSH

# Apply sensisble zsh settings
source ~/dotfiles/zsh/zshopt

# Bind C+Space to accept the current suggestion
bindkey '^ ' autosuggest-accept

# Load aliases
source ~/dotfiles/zsh/aliases.zsh

# Apply FZF configuration
source ~/dotfiles/zsh/fzf.zsh

# <<<<<<<<<<<---------  ZSH

# load zoxide
eval "$(zoxide init zsh)"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

export PATH="$HOME/.local/bin:$PATH"
